export const APP = { // GLOBAL - APP
  RESET_STORE: 'RESET_STORE',
  GLOBAL: {
    SET_REQUEST_LOADING: 'SET_REQUEST_LOADING', // GLOBAL - LOADING
    INCREASE_REQUEST_COUNT: 'INCREASE_REQUEST_COUNT', // 增加请求数
    DECREASE_REQUEST_COUNT: 'DECREASE_REQUEST_COUNT' // 减少请求数
  }
}

export const USER = { // MODULE - USER
  RESET_STORE: 'RESET_STORE',
  USER: {
    SET_TOKEN: 'SET_TOKEN'
  }
}
